### ISSUE TITLE
config options - server side [feature]

### ISSUE THREAD

**Issue by Unleashed75** [151chit/BlockoMorph#2]
I would like to see a server config option to limit what a player can turn into.
And the client to only see a list of allowed morphs would be nice.

Being able to be turn into a Redstone dot high on a roof or in a small air gap could be tricky to find them if using this mod for games of Hide n Seek.

Nice mod though!

**Comment by 151chit** [comment]
I thought about this when I started developing, I'll try to implement it

**Comment by 151chit** [comment]
Ok I will add this, at the moment I have done 10% of the planned, I will also add the unmask button to the player in the GUI "Configure my block"

**Comment by 151chit** [comment]
Configuration parameters are 50% developed, at the moment there will be 5 parameters:
- black list of blocks
- white list of blocks
- list mode (determines whether the mod will work in black, white list mode or there will be no restrictions)
- the player dies after destruction (if true, then the player dies immediately after destruction, if false, then the player is unmasked after destruction)
- operators can modify the config (if true, then a player with operator rights can change the parameters from the GUI in the game, if false, then the parameters can only be changed manually by changing the file when the server is turned off) (this parameter cannot be changed by operators even when the parameter is on)

It remains to add a configuration command, a list filter "only full blocks", an unmasking button and porting to all versions of the game

![b_op](https://github.com/user-attachments/assets/1405cbb4-cd34-4c7c-9849-bfe369f59d00)
![b_op2](https://github.com/user-attachments/assets/ad0c9ed2-c2c8-40c7-bad3-1f27ed3c68cc)
(The GUIs are not yet finished in cosmetic terms)

**Comment by 151chit** [comment]
At the moment I have added all new functions to the mod on Forge version 1.20.1, now I will port it to other versions and then publish it. In the settings there is a boolean parameter "solidBlocksOnly" prohibiting all incomplete blocks on top of access lists, also there is a tab of saved blocks, where you can write frequently used blocks and also a tab showing only blocks available with the current configuration. And also there is a command for managing the config. In the GUI of block selection there is an unmasking button, allowing you to return to the skin of Steve.

**Comment by 151chit** [comment]
Neoforge 1.20.4 and 1.20.6 coming soon

**Comment by 151chit** [comment]
That's it, I've added all the new features and released all versions including 1.20.4 and 1.20.6, if you find any errors, please report them.
